# Análise Nodal

![](img/3nos4ramos.png)

In [2]:
import numpy as np
# exemplo de aplicação Análise Nodal
A = np.zeros((3,4))
A[0,0] = A[0,1]= A[1,2] = A[2,3] = 1
A[1,1]= A[2,0]= -1
print(" A : Matriz de Incidência Nós-Ramos \n", A)
# Vetor Fonte de Corrente de ramo
Is = np.zeros((4,1)) # não tem fonte de corrente neste exemplo
print(" Is : Vetor Fonte de Corrente Ramo \n", Is)
# Vetor Fonte de Tensão de ramo
Vs = np.zeros((4,1))
Vs[0,0] = 10
print(" Vs : Vetor Fonte de Tensão Ramo \n", Vs)
# Condutâncias de ramos
G = np.zeros((4,4))
G[0,0] = 1e10 # alta condutância -- baixa resistência
G[1,1]= 1./2
G[2,2] = 1./3
G[3,3] = 1./5
print(" G : Condutâncias de Ramos \n", G)
Is = np.matrix(Is)
Vs = np.matrix(Vs)
G = np.matrix(G)
A = np.matrix(A)

Gbarra = A*G*A.T
print(" Gbarra : Condutâncias de Nós \n", Gbarra)
E = Gbarra.I*A*(G*Vs-Is)
print(" E : Tensão de Nodal \n", E)
V = A.T*E
print(" V : Tensão em cada Ramo \n", V)
I=Is+G*(V-Vs)
print(" I : Corrente em cada Ramo \n", I)

 A : Matriz de Incidência Nós-Ramos 
 [[ 1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [-1.  0.  0.  1.]]
 Is : Vetor Fonte de Corrente Ramo 
 [[0.]
 [0.]
 [0.]
 [0.]]
 Vs : Vetor Fonte de Tensão Ramo 
 [[10.]
 [ 0.]
 [ 0.]
 [ 0.]]
 G : Condutâncias de Ramos 
 [[1.00000000e+10 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.00000000e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33333333e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e-01]]
 Gbarra : Condutâncias de Nós 
 [[ 1.00000000e+10 -5.00000000e-01 -1.00000000e+10]
 [-5.00000000e-01  8.33333333e-01  0.00000000e+00]
 [-1.00000000e+10  0.00000000e+00  1.00000000e+10]]
 E : Tensão de Nodal 
 [[ 5.00004482]
 [ 3.00002245]
 [-4.999956  ]]
 V : Tensão em cada Ramo 
 [[10.00000083]
 [ 2.00002237]
 [ 3.00002245]
 [-4.999956  ]]
 I : Corrente em cada Ramo 
 [[ 8.27403710e+03]
 [ 1.00001118e+00]
 [ 1.00000748e+00]
 [-9.99991201e-01]]


## Considere o ramo (R + Vs): Fonte de Tensão com Resistência Série

![](img/2nos3ramos.png)

In [3]:
import numpy as np
A = np.zeros((2,3))
#ramo 1 saí do nó 1 e chega no nó GND
A[0,0] = 1
#ramo 2 saí do nó 1 e chega no nó 2
A[0,1] = 1
A[1,1] = -1
#ramo 3 saí do nó 2 e chega no nó GND
A[1,2] = 1
print(" A : Matriz de Incidência Nós-Ramos \n", A)

# Vetor Fonte de Corrente de ramo
Is = np.zeros((3,1)) # não tem fonte de corrente neste exemplo
print(" Is : Vetor Fonte de Corrente Ramo \n", Is)
# Vetor Fonte de Tensão de ramo
Vs = np.zeros((3,1))
Vs[0,0] = 10
print(" Vs : Vetor Fonte de Tensão Ramo \n", Vs)
# Condutâncias de ramos
G = np.zeros((3,3))
G[0,0] = 1./5
G[1,1]= 1./2
G[2,2] = 1./3

print(" G : Condutâncias de Ramos \n", G)
Is = np.matrix(Is)
Vs = np.matrix(Vs)
G = np.matrix(G)
A = np.matrix(A)

Gbarra = A*G*A.T
print(" Gbarra : Condutâncias de Nós \n", Gbarra)
E = Gbarra.I*A*(G*Vs-Is)
print(" E : Tensão de Nodal \n", E)
V = A.T*E
print(" V : Tensão em cada Ramo \n", V)
I=Is+G*(V-Vs)
print(" I : Corrente em cada Ramo \n", I)

 A : Matriz de Incidência Nós-Ramos 
 [[ 1.  1.  0.]
 [ 0. -1.  1.]]
 Is : Vetor Fonte de Corrente Ramo 
 [[0.]
 [0.]
 [0.]]
 Vs : Vetor Fonte de Tensão Ramo 
 [[10.]
 [ 0.]
 [ 0.]]
 G : Condutâncias de Ramos 
 [[0.2        0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
 Gbarra : Condutâncias de Nós 
 [[ 0.7        -0.5       ]
 [-0.5         0.83333333]]
 E : Tensão de Nodal 
 [[5.]
 [3.]]
 V : Tensão em cada Ramo 
 [[5.]
 [2.]
 [3.]]
 I : Corrente em cada Ramo 
 [[-1.]
 [ 1.]
 [ 1.]]


## Considere uma fonte de Corrente

![](img/2nos4ramos.png)

In [5]:
import numpy as np
A = np.zeros((2,4))
#ramo 1 saí do nó 1 e chega ao nó GND
A[0,0] = 1
#ramo 2 saí do nó 1 e chega ao nó GND
A[0,1] = 1
#ramo 3 saí do nó 1 e chega ao nó 2
A[0,2] = 1
A[1,2] = -1
#ramo 4 saí do nó 2 e chega ao nó GND
A[1,3] = 1
print(" A : Matriz de Incidência Nós-Ramos \n", A)

# Vetor Fonte de Corrente de ramo
Is = np.zeros((4,1)) 
Is[0, 0] = -2
print(" Is : Vetor Fonte de Corrente Ramo \n", Is)
# Vetor Fonte de Tensão de ramo
Vs = np.zeros((4,1))
print(" Vs : Vetor Fonte de Tensão Ramo \n", Vs)
# Condutâncias de ramos
G = np.zeros((4,4))
G[0,0] = 1e-10  # baixa condutância -- alta resistência
G[1,1]= 1./5
G[2,2]= 1./2
G[3,3] = 1./3

print(" G : Condutâncias de Ramos \n", G)
Is = np.matrix(Is)
Vs = np.matrix(Vs)
G = np.matrix(G)
A = np.matrix(A)

Gbarra = A*G*A.T
print(" Gbarra : Condutâncias de Nós \n", Gbarra)
E = Gbarra.I*A*(G*Vs-Is)
print(" E : Tensão de Nodal \n", E)
V = A.T*E
print(" V : Tensão em cada Ramo \n", V)
I=Is+G*(V-Vs)
print(" I : Corrente em cada Ramo \n", I)

 A : Matriz de Incidência Nós-Ramos 
 [[ 1.  1.  1.  0.]
 [ 0.  0. -1.  1.]]
 Is : Vetor Fonte de Corrente Ramo 
 [[-2.]
 [ 0.]
 [ 0.]
 [ 0.]]
 Vs : Vetor Fonte de Tensão Ramo 
 [[0.]
 [0.]
 [0.]
 [0.]]
 G : Condutâncias de Ramos 
 [[1.00000000e-10 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.00000000e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.00000000e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.33333333e-01]]
 Gbarra : Condutâncias de Nós 
 [[ 0.7        -0.5       ]
 [-0.5         0.83333333]]
 E : Tensão de Nodal 
 [[5.]
 [3.]]
 V : Tensão em cada Ramo 
 [[5.]
 [5.]
 [2.]
 [3.]]
 I : Corrente em cada Ramo 
 [[-2.]
 [ 1.]
 [ 1.]
 [ 1.]]
