![](https://static.javatpoint.com/tutorial/numpy/images/numpy-tutorial.png)

https://www.tutorialspoint.com/numpy/numpy_quick_guide.htm


http://cs231n.github.io/python-numpy-tutorial/

[Apostila](pdf/numpyAp.pdf)




In [22]:
import numpy as np

z = 2 + 2j
print(np.angle(z,deg=1)) # dentro do numpy exite diversos rotinas implementadas

A = np.array([1,2,3]) 
print ('A= ', A)
B = np.array([[4, 2, 3], [1, 5, 8]])
print('B=\n', B)


45.0
A=  [1 2 3]
B=
 [[4 2 3]
 [1 5 8]]


In [23]:
# type(A)
print("Dimensao de A eh %d " %A.ndim)  # Numero de dimensoes do Array
print (" O Shape  de A eh ", A.shape)
print("Dimensao de B eh %d " %B.ndim)  
print (" O Shape  de B eh ", B.shape)



Dimensao de A eh 1 
 O Shape  de A eh  (3,)
Dimensao de B eh 2 
 O Shape  de B eh  (2, 3)


In [29]:
C = np.arange(15).reshape(5, 3)
print ('C=\n', C)
D = np.zeros((3, 5))
print ('D=\n', D)
E = np.arange(9,10,.1).reshape(2, 5)
print ('E=\n', E)

C=
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
D=
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
E=
 [[9.  9.1 9.2 9.3 9.4]
 [9.5 9.6 9.7 9.8 9.9]]


# Matrizes

In [40]:
A = np.matrix([[1, 2, 2], [-8, 9, 10]])
B = np.matrix([[-1, 12, 0], [1, -9, 10]])
C =A - B
print('A transposta de C eh\n ',C.T)

A transposta de C eh
  [[  2  -9]
 [-10  18]
 [  2   0]]


In [41]:
A.I

matrix([[ 0.37164751, -0.07816092],
        [ 0.16858238,  0.01609195],
        [ 0.14559387,  0.02298851]])

In [44]:
X = np.matrix([[2, 4],[1,0]])
X.I

matrix([[ 0.  ,  1.  ],
        [ 0.25, -0.5 ]])

# Aplicação Circuitos Elétricos

In [2]:
import numpy as np
# exemplo de aplicação Análise Nodal
A = np.zeros((3,4))
A[0,0] = A[0,1]= A[1,2] = A[2,3] = 1
A[1,1]= A[2,0]= -1
A

array([[ 1.,  1.,  0.,  0.],
       [ 0., -1.,  1.,  0.],
       [-1.,  0.,  0.,  1.]])

In [3]:
# Vetor Fonte de Corrente de ramo
Is = np.zeros((4,1)) # não tem fonte de corrente neste exemplo
# Vetor Fonte de Tensão de ramo
Vs = np.zeros((4,1))
Vs[0,0] = 10
Vs

array([[10.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [4]:
# Condutâncias de ramos
G = np.zeros((4,4))
G[0,0] = 1e10
G[1,1]= 1./2
G[2,2] = 1./3
G[3,3] = 1./5
G

array([[1.00000000e+10, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.33333333e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e-01]])

In [5]:
Is = np.matrix(Is)
Vs = np.matrix(Vs)
G = np.matrix(G)
A = np.matrix(A)
Gbarra = A*G*A.T
Gbarra

matrix([[ 1.00000000e+10, -5.00000000e-01, -1.00000000e+10],
        [-5.00000000e-01,  8.33333333e-01,  0.00000000e+00],
        [-1.00000000e+10,  0.00000000e+00,  1.00000000e+10]])

In [6]:
Is_no = A*(G*Vs - Is)
Is_no

matrix([[ 1.e+11],
        [ 0.e+00],
        [-1.e+11]])

In [8]:
E = Gbarra.I*Is_no
#E = Gbarra.I*A*(G*Vs-Is)
E

matrix([[ 5.00003052],
        [ 3.00003052],
        [-4.99993896]])

In [9]:
V = A.T*E
V

matrix([[ 9.99996948],
        [ 2.        ],
        [ 3.00003052],
        [-4.99993896]])

In [10]:
I=Is+G*(V-Vs)
I

matrix([[-3.05175781e+05],
        [ 1.00000000e+00],
        [ 1.00001017e+00],
        [-9.99987793e-01]])